### ISSUE TITLE
refactor: @tanstack/react-query의 기본 Error 타입 AxiosError로 변경

### ISSUE THREAD

**Issue by sukvvon** [Anifriends/Anifriends-Frontend#127]
## 개선해야 되는 코드 혹은 기능에 대해서 적어주세요 

기본 useMutation이나 useQuery를 사용하면 error에 대한 타입이 기본 Error여서 일일히 AxiosError로 변경해줘야합니다 

## 원하는 개선 방향

기본 useMutation이나 useQuery를 사용하면 error에 대한 타입이 기본 Error이지만 AxiosError로 변경하려고 합니다 

## 생각 중인 기능 추가 방안

- [ ] @tanstack/react-query의 기본 error 타입 Error에서 AxiosError로 변경
- [ ] signin 페이지의 useMutaion의 generic로 명시한 항목 제거
- [ ] signup 페이지의 useMutaion의 generic로 명시한 항목 제거

### 변경 전
![image](https://github.com/Anifriends/Anifriends-Frontend/assets/66409882/8a4d7846-6813-49f9-a850-134c90468065)

### 변경 후
![image](https://github.com/Anifriends/Anifriends-Frontend/assets/66409882/9c90e46e-426d-4ba4-81e6-0af47585f652)

* #124 완료 후 진행할 예정입니다!!

**Comment by DongjaJ** [comment]
어떻게 바꾼다는 것인지 이해하지 못했습니다.
onError에서 axios.isAxiosError(error) 함수로 타입가드를 할수 있지 않나요?

**Comment by sukvvon** [comment]
> 어떻게 바꾼다는 것인지 이해하지 못했습니다. onError에서 axios.isAxiosError(error) 함수로 타입가드를 할수 있지 않나요?

https://tanstack.com/query/latest/docs/react/typescript#registering-a-global-error

@DongjaJ 위 공식문서에 관련 자료가 있어 바꾸려고 d.ts 파일을 통해 덮어씌우려고합니다!!
